#!/bin/csh -f
cd /n/work00/osanmasa/hepmc3ChargedDijet
source setup.csh
setenv what  hepmc3ChargedDijet
set line = 0
@ line = ( $SLURM_ARRAY_TASK_ID )
setenv fullFile `head -${line} Todo_DJ-Jetscape-run-20.txt | tail -1`
setenv indir `dirname $fullFile`
setenv myfile `basename $fullFile`
setenv rootoutfile  /n/work00/osanmasa/hepmc3ChargedDijet/outputs/hepmc3-DJ-Jetscape-run-20/data/hepmc3-DJ-Jetscape-run-20-$myfile.root
setenv Log      /n/work00/osanmasa/hepmc3ChargedDijet/outputs/hepmc3-DJ-Jetscape-run-20/logs/hepmc3-DJ-Jetscape-run-20-$myfile.log
./${what} $fullFile $rootoutfile ../HepPDT/HepPDT-3.04.01/data/particle.tbl 20 >& $Log
cd /n/work00/osanmasa/hepmc3ChargedDijet
