
export JETSCAPE_HEPMCFOL=/projappl/project_2003583/JETSCAPE_software

export HEPMC=$JETSCAPE_HEPMCFOL/HepMC3/hepmc3-install
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JETSCAPE_HEPMCFOL/HepMC3/hepmc3-install/lib
export HEPPDT=$JETSCAPE_HEPMCFOL/HepPDT/HepPDT-3.04.01-install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JETSCAPE_HEPMCFOL/HepPDT/HepPDT-3.04.01-install/lib
